/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lastversion;

import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.JOptionPane;


class Info{
    public String ip;
    public int data;
    Info(String ip,int data){
        this.ip=ip;
        this.data=data;
    }
}
class Infotmp implements Comparator<Info>{

@Override
public int compare(Info e1, Info e2) {
if(e1.data== e2.data){
return 0;
} else {
return -1;
}
}
}
class InfoSort implements Comparator<Info>{

        @Override
        public int compare(Info e1, Info e2) {
            return (int) (e1.data - e2.data);
          
        }

        
}
class VirtualResponseNode{
        public String ip;
        public int port;
        public int data;
        public String binary;
        public ArrayList<Info> infoObj = new ArrayList<>();  
        public VirtualResponseNode(String ip,int port,int data){
            this.ip=ip;
            this.port=port;
            this.data=data;
            //this.=null;
        }
}
class Node {
        public int no;
        public String ip;
        public int port;
        public int data;
        public String binary;
 
        public Node(int no,String ip,int port,int data){
            this.no=no;
            this.ip=ip;
            this.port=port;
            this.data=data;
        }
        
        
        public static String xor(String p1,String p2)
        {
            StringBuilder sb = new StringBuilder();
            for(int i = 0; i < p1.length()/2; i++)
            sb.append((p1.charAt(i) ^ p2.charAt(i)));
            String result = sb.toString();
            System.out.println("\n"+result+"\n");
            return result;
        }

        public static String toBinary(final String ip)
        {
            int len      = ip.length();
            int addr     = 0;
            int fullAddr = 0;
            char [] out  = new char[32];

            // Parse the four segments of the IP address.
            for (int i = 0; i < len; i++) {
                char digit = ip.charAt(i);
                if (digit != '.') {
                    addr = addr * 10 + (digit - '0');
                } 
                else {
                        fullAddr = (fullAddr << 8) | addr;
                    addr = 0;
                }
            }
            fullAddr = (fullAddr << 8) | addr;

             // At this point, fullAddr holds the IP address as a 32-bit integer.
             for (int i = 0; i < 32; i++, fullAddr <<= 1)
                out[i] = ((fullAddr & 0x80000000) != 0) ? '1' : '0';
            
             return new String(out);
        }   
}
public class DataSetup extends javax.swing.JFrame {

    /**
     * Creates new form DataSetup
     */
    public static int no=0;
    Node node=null;
    VirtualResponseNode vNode=null;
    public static ArrayList<Node> nodeObj = new ArrayList<>();
    public static ArrayList<VirtualResponseNode> virtualResponseNodeObj = new ArrayList<>();
           
           
    public DataSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("DATA SETUP");

        jLabel2.setText("IP");

        jTextField1.setText("                  ");

        jLabel3.setText("Port");

        jTextField2.setText("                      ");

        jLabel4.setText("Data");

        jTextField3.setText("                                     ");

        jLabel5.setText("IP");

        jTextField5.setText("                      ");

        jLabel6.setText("Data");

        jTextField6.setText("                                     ");

        jTextField4.setText("                  ");

        jLabel7.setText("Port");

        jLabel8.setText("IP");

        jTextField8.setText("                      ");

        jLabel9.setText("Data");

        jTextField9.setText("                                     ");

        jTextField7.setText("                  ");

        jLabel10.setText("Port");

        jLabel11.setText("IP");

        jTextField11.setText("                      ");

        jLabel12.setText("Data");

        jTextField12.setText("                                     ");

        jTextField10.setText("                  ");

        jLabel13.setText("Port");

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ADD MORE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButton3)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                String ip_in;
                int data_in;
                int port_in;
                System.out.println("test"+jTextField4.getText().trim() + jTextField5.getText().trim() + jTextField6.getText().trim())            ;
                if(!jTextField1.getText().trim().equals("") && !jTextField2.getText().trim().equals("") && !jTextField3.getText().trim().equals(""))
                {
                node=new Node(++no,jTextField1.getText().trim(),Integer.parseInt(jTextField2.getText().trim()),Integer.parseInt(jTextField3.getText().trim()));             
                nodeObj.add(node);            
                if(no ==32 || no==2 || no==4 || no== 8 || no==16)
                {
                    vNode=new VirtualResponseNode(jTextField1.getText().trim(),Integer.parseInt(jTextField2.getText().trim()),Integer.parseInt(jTextField3.getText().trim()));             
                    virtualResponseNodeObj.add(vNode);
                }
                }
//                System.out.println("test"+jTextField4.getText().trim() + Integer.parseInt(jTextField5.getText().trim()) + Integer.parseInt(jTextField6.getText().trim())            );
                if(!jTextField4.getText().trim().equals("") && !jTextField5.getText().trim().equals("") && !jTextField6.getText().trim().equals(""))
                {
                    System.out.println("test"+jTextField4.getText().trim() + Integer.parseInt(jTextField5.getText().trim()) + Integer.parseInt(jTextField6.getText().trim())            );
                node=new Node(++no,jTextField4.getText().trim(),Integer.parseInt(jTextField5.getText().trim()),Integer.parseInt(jTextField6.getText().trim()));             
                nodeObj.add(node);            
                if(no ==32 || no==2 || no==4 || no== 8 || no==16)
                {
                    vNode=new VirtualResponseNode(jTextField4.getText().trim(),Integer.parseInt(jTextField5.getText().trim()),Integer.parseInt(jTextField6.getText().trim()));             
                    virtualResponseNodeObj.add(vNode);
                }
                }
                
                if(!jTextField7.getText().trim().equals("") && !jTextField8.getText().trim().equals("") && !jTextField9.getText().trim().equals(""))
                {
                node=new Node(++no,jTextField7.getText().trim(),Integer.parseInt(jTextField8.getText().trim()),Integer.parseInt(jTextField9.getText().trim()));             
                nodeObj.add(node);            
                if(no ==32 || no==2 || no==4 || no== 8 || no==16)
                {
                    vNode=new VirtualResponseNode(jTextField7.getText().trim(),Integer.parseInt(jTextField8.getText().trim()),Integer.parseInt(jTextField9.getText().trim()));             
                    virtualResponseNodeObj.add(vNode);
                }
                }
                
                if(!jTextField10.getText().trim().equals("") && !jTextField11.getText().trim().equals("") && !jTextField12.getText().trim().equals(""))
                {
                node=new Node(++no,jTextField10.getText().trim(),Integer.parseInt(jTextField11.getText().trim()),Integer.parseInt(jTextField12.getText().trim()));             
                nodeObj.add(node);            
                if(no ==32 || no==2 || no==4 || no== 8 || no==16)
                {
                    vNode=new VirtualResponseNode(jTextField10.getText().trim(),Integer.parseInt(jTextField11.getText().trim()),Integer.parseInt(jTextField12.getText().trim()));             
                    virtualResponseNodeObj.add(vNode);
                }
                }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");jTextField4.setText(""); jTextField5.setText("");jTextField6.setText("");jTextField7.setText("");jTextField8.setText("");jTextField9.setText("");jTextField10.setText("");        jTextField11.setText("");
        jTextField12.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Info info=null;
            for(VirtualResponseNode vrNode : virtualResponseNodeObj){
                System.out.println(vrNode.ip);
                for(Node aNode : nodeObj){
                    info=new Info(aNode.ip,aNode.data);
                    vrNode.infoObj.add(info);
                }
            }   
            for(VirtualResponseNode vrNode : virtualResponseNodeObj){
                System.out.println("ip"+vrNode.ip);
                System.out.println("ip"+vrNode.data);
                System.out.println("Info Node details of "+ vrNode.ip);
                for(Info infoNode : vrNode.infoObj)
                {
                    System.out.println("infoNode ip" + infoNode.ip);
                    System.out.println("infoNode ip" + infoNode.data);
                }
            }
            String inputIPAddress=null;
            JOptionPane.showMessageDialog(null, "Nodes are added Successfully!!!");
          //  JOptionPane.showConfirmDialog(rootPane, evt);
          // int dialogResult = JOptionPane.showConfirmDialog (null, "The ip details are added successfully!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");jTextField4.setText(""); jTextField5.setText("");jTextField6.setText("");jTextField7.setText("");jTextField8.setText("");jTextField9.setText("");jTextField10.setText("");        jTextField11.setText("");
        jTextField12.setText("");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DataSetup dataSetUp=new DataSetup();
                dataSetUp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
